"""Calibrate defensible interpretations of the paper's HTMP parameter.

The PRISM paper says only that its 8000 x 4000 matrices are "generated by
HTMP" following Hodgkinson et al.  The cited paper defines the limiting
parameter through beta * N -> kappa, while its finite beta-Laguerre sampler
takes beta directly.  This script tests the plausible API interpretations
without selecting a sample size or convergence horizon from PRISM's formula.
"""

from __future__ import annotations

import json
import math
import os
import time
from concurrent.futures import ProcessPoolExecutor
from dataclasses import dataclass

import numpy as np
from scipy.linalg import eigvalsh_tridiagonal

from spectral_prism import bounded_prism_alpha, residual_error


N_ROWS = 8_000
N_COLUMNS = 4_000
KAPPAS = (0.1, 0.5, 100.0)
HORIZON = 32
SEED = 202601

# Read directly from the iteration-domain panels in Figure D.2.  The brackets
# allow one plotting-marker uncertainty and are intentionally fixed before
# evaluating any sampler candidate.
PAPER_FIRST_HIT_BRACKETS = {
    0.1: {"fro_1e-2": (17, 19), "fro_1e-4": (18, 20)},
    0.5: {"fro_1e-2": (17, 19), "fro_1e-4": (18, 20)},
    100.0: {"fro_1e-2": (7, 9), "fro_1e-4": (7, 10)},
}


@dataclass(frozen=True)
class Candidate:
    name: str
    divisor: float

    def beta(self, kappa: float) -> float:
        return kappa / self.divisor


CANDIDATES = (
    Candidate("cited_asymptotic_beta_eq_kappa_over_columns", N_COLUMNS),
    Candidate("rows_as_ensemble_size_beta_eq_kappa_over_rows", N_ROWS),
    Candidate("two_sided_scaling_beta_eq_2kappa_over_columns", N_COLUMNS / 2),
    Candidate("sqrt_scaled_beta_eq_kappa_over_sqrt_columns", math.sqrt(N_COLUMNS)),
    Candidate("finite_sampler_direct_beta_eq_kappa", 1.0),
)


def sample_singular_values(beta: float, seed: int) -> tuple[np.ndarray, dict[str, float | int]]:
    """Use the finite beta-Laguerre construction cited by the HTMP paper."""
    rng = np.random.default_rng(seed)
    d_df = beta * (N_ROWS - np.arange(N_COLUMNS))
    t_df = beta * (N_COLUMNS - 1 - np.arange(N_COLUMNS - 1))
    d = np.sqrt(rng.chisquare(d_df))
    t = np.sqrt(rng.chisquare(t_df))
    diagonal = d**2
    diagonal[:-1] += t**2
    off_diagonal = d[1:] * t
    eigenvalues = eigvalsh_tridiagonal(
        diagonal, off_diagonal, check_finite=True, lapack_driver="sterf"
    )
    negative_tolerance = 1e-10 * max(1.0, float(eigenvalues[-1]))
    if float(eigenvalues[0]) < -negative_tolerance:
        raise ArithmeticError("corrected bidiagonal product is not PSD")
    eigenvalues = np.maximum(eigenvalues, 0)
    singular_values = np.sqrt(eigenvalues)
    frobenius = float(np.linalg.norm(singular_values))
    if frobenius == 0:
        raise ArithmeticError("zero beta-Laguerre sample")
    singular_values /= frobenius
    return singular_values, {
        "zero_chi_draws": int(np.sum(d == 0) + np.sum(t == 0)),
        "zero_eigenvalues": int(np.sum(eigenvalues == 0)),
        "minimum_positive_eigenvalue": float(
            np.min(eigenvalues[eigenvalues > 0])
        ),
        "maximum_eigenvalue": float(eigenvalues[-1]),
    }


def first_hit(values: list[float], threshold: float) -> int | None:
    return next((index for index, value in enumerate(values) if value <= threshold), None)


def evaluate(task: tuple[Candidate, float]) -> dict[str, object]:
    candidate, kappa = task
    started = time.perf_counter()
    beta = candidate.beta(kappa)
    singular_values, audit = sample_singular_values(beta, SEED)
    errors: list[float] = []
    alphas: list[float] = []
    for iteration in range(HORIZON + 1):
        error_fro, _ = residual_error(singular_values)
        errors.append(error_fro)
        if iteration == HORIZON:
            break
        alpha, _ = bounded_prism_alpha(singular_values)
        alphas.append(alpha)
        residual = 1 - singular_values**2
        singular_values *= 1 + 0.5 * residual + alpha * residual**2
    hits = {
        "fro_1e-2": first_hit(errors, 1e-2),
        "fro_1e-4": first_hit(errors, 1e-4),
    }
    brackets = PAPER_FIRST_HIT_BRACKETS[kappa]
    hit_checks = {
        key: hits[key] is not None and low <= hits[key] <= high
        for key, (low, high) in brackets.items()
    }
    return {
        "candidate": candidate.name,
        "kappa": kappa,
        "beta": beta,
        "seed": SEED,
        "normalization": "singular values divided by Frobenius norm",
        "sampler_audit": audit,
        "first_hits": hits,
        "paper_first_hit_brackets": brackets,
        "hit_checks": hit_checks,
        "matches_all_anchors": all(hit_checks.values()),
        "alpha_profile": alphas,
        "error_fro_profile": errors,
        "runtime_seconds": time.perf_counter() - started,
    }


def main() -> int:
    started = time.perf_counter()
    tasks = [(candidate, kappa) for candidate in CANDIDATES for kappa in KAPPAS]
    affinity = len(os.sched_getaffinity(0)) if hasattr(os, "sched_getaffinity") else 1
    workers = min(6, affinity, len(tasks))
    with ProcessPoolExecutor(max_workers=workers) as executor:
        rows = list(executor.map(evaluate, tasks))
    candidate_matches = {
        candidate.name: all(
            row["matches_all_anchors"]
            for row in rows
            if row["candidate"] == candidate.name
        )
        for candidate in CANDIDATES
    }
    payload = {
        "schema": "prism-htmp-parameter-calibration-v1",
        "paper_dimensions": [N_ROWS, N_COLUMNS],
        "paper_source": "arXiv:2601.22137 Figure D.2",
        "cited_source": "arXiv:2506.03470 Appendix E.1 and Algorithm 2",
        "predeclared_horizon": HORIZON,
        "predeclared_seed": SEED,
        "worker_processes": workers,
        "logical_cpu_affinity": affinity,
        "candidate_matches_all_kappas": candidate_matches,
        "matching_candidates": [
            name for name, matched in candidate_matches.items() if matched
        ],
        "rows": rows,
        "runtime_seconds": time.perf_counter() - started,
    }
    print("HTMP_CALIBRATION=" + json.dumps(payload, sort_keys=True, separators=(",", ":")))
    if not payload["matching_candidates"]:
        print("HTMP_CALIBRATION_NO_INTERPRETATION_MATCHED_ALL_PUBLISHED_ANCHORS")
        return 8
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
